// Audit tests for Crystal::ReduceRaypath orbit invariant property.
//
// Background (scratchpad/scrum-filter-architecture-refactor/explore-reduce-raypath-audit/):
//   Task #209 fixed sigma_a≠0 + P+D canonicalization but covered only one case.
//   This audit systematically verifies orbit invariant across 5 dimensions:
//     H1: prism + kSymP + sigma_a≠0
//     H2: kSymB (basal 1↔2 + pyramid upper↔lower)
//     H3: pyramid crystal (双位编码 face_id 13..18/23..28)
//     H4: multi-segment (rp.size up to kMaxHits=8)
//     H5: mixed crystal type config
//
// Orbit invariant property:
//   For any raypath rp and any g in the symmetry group G generated by the active
//   symmetries, ReduceRaypath(rp) == ReduceRaypath(g·rp). The orbit {g·rp : g ∈ G}
//   is enumerated via Crystal::ExpandRaypath. Every orbit member must reduce to
//   the same canonical representative.
//
// On failure: this audit produces a minimal repro (failing orbit member + the two
// distinct canonicals) — the same pattern as #209's fix scope.

#include <gtest/gtest.h>

#include <string>
#include <vector>

#include "config/filter_config.hpp"
#include "core/crystal.hpp"
#include "core/def.hpp"

namespace lumice {
namespace {

// Format a raypath vector for diagnostic output.
std::string FormatRaypath(const std::vector<IdType>& rp) {
  std::string s = "{";
  for (size_t i = 0; i < rp.size(); i++) {
    if (i > 0) {
      s += ", ";
    }
    s += std::to_string(rp[i]);
  }
  s += "}";
  return s;
}

// Verify the orbit invariant for one (crystal, symmetry, sigma_a, d_applicable, rp_seed) tuple.
// Returns ::testing::AssertionResult so EXPECT_TRUE prints the failing detail.
::testing::AssertionResult VerifyOrbitInvariant(const Crystal& crystal, uint8_t symmetry, int sigma_a,
                                                 bool d_applicable, const std::vector<IdType>& rp_seed) {
  auto canonical_seed = crystal.ReduceRaypath(rp_seed, symmetry, sigma_a, d_applicable);
  auto orbit = crystal.ExpandRaypath(rp_seed, symmetry, sigma_a, d_applicable);
  if (orbit.empty()) {
    return ::testing::AssertionFailure()
           << "ExpandRaypath returned empty orbit for seed " << FormatRaypath(rp_seed);
  }
  for (const auto& member : orbit) {
    auto canonical_member = crystal.ReduceRaypath(member, symmetry, sigma_a, d_applicable);
    if (canonical_member != canonical_seed) {
      return ::testing::AssertionFailure()
             << "Orbit invariant broken:"
             << "\n  seed:               " << FormatRaypath(rp_seed)
             << "\n  seed canonical:     " << FormatRaypath(canonical_seed)
             << "\n  orbit member:       " << FormatRaypath(member)
             << "\n  member canonical:   " << FormatRaypath(canonical_member)
             << "\n  symmetry=" << static_cast<int>(symmetry) << " sigma_a=" << sigma_a
             << " d_applicable=" << d_applicable;
    }
  }
  return ::testing::AssertionSuccess();
}

}  // namespace

// ============================================================================
// H2: kSymB orbit invariant
// ============================================================================
// kSymB encodes basal 1↔2 + pyramid upper [13..18]↔lower [23..28]; prism faces unchanged.
// Coverage: B-only / P+B / D+B / P+D+B across prism and pyramid crystals.

TEST(H2_KSymB_Audit, BasalReflect_Prism) {
  // Prism with basal+prism raypath: B flips basal 1↔2, prism face unchanged.
  Crystal prism = Crystal::CreatePrism(1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymB, 0, false, { 1, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymB, 0, false, { 2, 7 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymB, 0, false, { 1, 3, 2 }));
}

TEST(H2_KSymB_Audit, BasalAndPyramidReflect_Pyramid) {
  // Pyramid with basal+upper raypath: B flips basal 1↔2 AND pyramid 13↔23.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymB, 0, false, { 1, 13 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymB, 0, false, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymB, 0, false, { 23, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymB, 0, false, { 1, 13, 5, 23 }));
}

TEST(H2_KSymPB_Audit, PrismRaypath_Prism) {
  // P+B on prism: P rotates prism pri, B flips basal — independent symmetries.
  Crystal prism = Crystal::CreatePrism(1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, false, { 3, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, false, { 1, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, false, { 1, 3, 5 }));
}

TEST(H2_KSymPB_Audit, MixedRaypath_Pyramid) {
  // P+B on pyramid with basal+upper+prism: full interaction.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, false, { 1, 13 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, false, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, false, { 1, 13, 5 }));
}

TEST(H2_KSymDB_Audit, PrismRaypath_Prism) {
  // D+B on prism (sigma_a=0): D rotates prism pri via reflection, B flips basal.
  Crystal prism = Crystal::CreatePrism(1.0f);
  uint8_t sym = FilterConfig::kSymD | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 3, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 1, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 1, 3, 7 }));
}

TEST(H2_KSymDB_Audit, MixedRaypath_Pyramid) {
  // D+B on pyramid: D reflects pri on prism + pyramid (same pri arithmetic),
  // B flips basal + upper↔lower pyramid. Most complex single-pair interaction.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymD | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13, 5, 23 }));
}

TEST(H2_KSymPDB_Audit, FullSymmetry_Prism) {
  // P+D+B on prism: full hexagonal symmetry group.
  Crystal prism = Crystal::CreatePrism(1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymD | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 3, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 1, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 5, true, { 3, 5 }));  // non-zero sigma_a
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 1, 3, 5, 7 }));
}

TEST(H2_KSymPDB_Audit, FullSymmetry_Pyramid) {
  // P+D+B on pyramid: full symmetry group including upper↔lower pyramid swap.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymD | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13, 5, 23 }));
}

}  // namespace lumice
