// CLI<->GUI export parity — the gate that makes "what the GUI shows is what the exported config
// renders" a proposition something can turn red on.
//
// The proposition. A document is loaded in the GUI, a scene's view settings are applied, the run
// completes, and two images are produced from that one document:
//   (1) the GUI side, through the SAME per-frame PreviewParams assembly the product uses
//       (src/gui/app_panels.cpp fills g_preview_vp.params from GuiState every frame), rendered
//       off-screen by gui::ExportPreviewPng;
//   (2) the CLI side, by handing gui::BuildExportJsonOrWarn's output to the Lumice CLI binary in
//       a child process and reading the image it writes.
// The two are compared by PSNR. Nothing here re-encodes a field by hand: both sides come out of
// production functions, which is the point — a fixture that rebuilt the export JSON itself would
// be a second mirror of the very code under test.
//
// Why a category of its own, in a directory of its own. Everything under test/gui/visual/ compares
// a capture against a COMMITTED reference image and is therefore regenerated by
// scripts/regen_gui_test_refs.py's GROUPS registry. This suite compares two renders made in the
// same run; it owns no committed asset and must never be added to that registry. The directory
// boundary says so structurally, so a contributor does not have to read this comment to find out.
//
// What it does NOT subsume. Three sibling comparisons stay where they are, because each answers a
// different proposition:
//   * test/e2e-correctness/test_ev_mode_relative_gui_parity.py compares the CLI's baked image
//     against the GUI's exposure FORMULA re-run over the same buffer through the C API. No GUI
//     process, no shader; its own docstring records that it strips the scene down to exposure
//     alone precisely because background / ray_color / grid / outline are baked by the CLI and
//     not by LUMICE_XyzToSrgbUint8.
//   * test/unit-correctness/gui/test_visible_mask_gui_parity.cpp and
//     test/unit-correctness/gui/test_horizon_gui_parity.cpp compare core's C++ predicate against a
//     CPU mirror of the GLSL one. They answer the SHAPE of the disagreement (which pixels, and on
//     which side of which boundary) — something a whole-image PSNR cannot express — and they need
//     no display, so they run on every platform. Complementary, not duplicated.
//
// ============================ Field coverage and measured sensitivity ========================
//
// The fields src/gui/file_io.cpp's BuildScene fills only on its kJsonExport arm, and what each
// scene does with them. The right-hand columns are MEASURED, not asserted: each is the PSNR the
// scene lands at when that one field is broken single-sided in the export arm (and only there),
// against a threshold of 25.5 / 26.0 dB. They are what says this gate can actually see the field.
//
// Two of the three scenes appear here. The third, `single_lens_rectilinear`, is not a field-
// coverage column: it holds the same view fields as `single_lens_angled` on purpose, and what it
// adds is the PROJECTION FAMILY axis described further down — it is the scene that can see the
// preview shader's relative-illumination factor, which neither equal-area column can.
//
//   field          | single_lens_angled       | broken | full_sky_dual_fisheye     | broken
//   ---------------|-------------------------|--------|---------------------------|--------
//   lens_type      | fisheye_equal_area      |  13.31 | dual_fisheye_equal_area   |   n/a
//   lens_fov       | 96 (non-default)        |  21.32 | 180                       |   n/a
//   visible        | upper                   |  16.85 | full                      |   n/a
//   view_azimuth   | 25, applied             |  19.56 | forced to 0 (full-sky)    |   n/a
//   view_elevation | 30, applied             |  15.31 | forced to 0 (full-sky)    |   n/a
//   view_roll      | 15, applied             |  19.53 | forced to 0 (full-sky)    |   n/a
//   background     | (0.10, 0.16, 0.28)      |  17.21 | (0.28, 0.14, 0.10)        |  18.16
//   resolution     | 4:3 + portrait -> 512x683 | canvas assert | no ratio -> 1024x512 |  n/a
//   horizon        | off                     |    n/a | off                       |  25.46
//   angular_dist   | on, {22, 46} deg        |  25.73 | on, {22, 46} deg          |  26.89
//   elevation      | on, 10 deg step         |  24.72 | on, 30 deg step           |    n/a
//   longitude      | on, 10 deg step         |  26.59 | on, 30 deg step           |  24.07
//   zenith_nadir   | on, zenith imaged       |    n/a | on, both imaged           |    n/a
//
// The zenith_nadir row's two "n/a"s are MEASURED, and they are a statement about the metric rather
// than about the field. A ring of the default 8 px radius covers roughly 150 pixels; deleting the
// CLI's nadir ring outright moved the full-sky scene by 0.02 dB, and UPWARD — the ring's presence
// costs a little parity (see below), so removing it reads as an improvement. A whole-frame PSNR
// cannot see this field, and the honest response is to say so rather than to pick a threshold that
// pretends otherwise.
//
// Enlarging the rings until it could see them was tried and rejected on the measurement: at radius
// 60 / 30 the full-sky scene falls from 27.62 to 27.09 dB, which is BELOW its threshold and within
// 0.2 dB of the smallest break it is supposed to catch. What that radius makes visible is not the
// marker's position but the two arms' edge models — the preview shader antialiases the ring with
// smoothstep over 1.5 px (overlayAuxLines), the CLI applies a hard 1.5 px distance test
// (server/render.cpp PostSnapshot) — so the enlarged ring would spend this gate's whole margin
// re-measuring a divergence it did not introduce, and would weaken every other row in the table by
// forcing the threshold down. Same reasoning as the GRID OPACITY note above, reaching the opposite
// action because a ring's edge is a fixed fraction of a ring rather than a removable alpha term.
//
// So what the markers are covered BY here is the export encoding, not the pixels: the fixture
// asserts that the exported document carries grid.zenith_nadir.enabled (ParseExportedRenderInfo),
// which is the half of the path that lives in BuildScene's export arm and the half that a
// regression would silently drop. Where the rings LAND is pinned by
// test/unit-correctness/gui/test_annotation_overlay_gui_parity.cpp, against the GUI's own former
// projection, at a resolution this metric does not have.
//
// The angular_dist row is broken two ways rather than one, because the two shapes it can fail in
// are independent and the weaker one sets the threshold. Shifting every circle by ONE degree in
// the CLI arm costs 23.68 / 25.38 dB; making the CLI draw only the FIRST of the two lines costs
// 25.73 / 26.89 dB, and that second, weaker break is the one the columns above report.
//
// The two grid rows are broken by dropping ONE line from the CLI arm — the smallest break the
// family has, since dropping the whole family is what a missing branch would do and costs far
// more. They are the reason the grid is worth two rows rather than one: a parallel and a meridian
// are different curves in the export arm (different Request field, different Overlay mask), and
// each column sees one of them clearly. The "n/a" on elevation / full_sky is measured, not
// assumed: at a 30 deg step the outermost parallel is the 80 deg one, which on a dual-fisheye
// frame is a small circle near each disc centre — dropping it moved that scene by 0.01 dB. Its
// meridians span a whole disc and cost 3.5 dB, which is where that scene's grid sensitivity lives.
// Symmetrically, single_lens_angled sees a dropped parallel at 2.3 dB and a dropped meridian at
// 0.47 dB, the latter under its threshold. So each grid break is caught by at least one column,
// which is the same structure the view-angle rows above already have.
//
// GRID OPACITY IS 1.0 IN BOTH SCENES, not the 0.3 a user gets, and this is the one appearance
// value either scene overrides. The reason is a divergence this gate is not the place to measure:
// the CLI blends an overlay line into radiance BEFORE the sRGB transfer curve (server/render.cpp
// PostSnapshot) while the preview shader blends it AFTER (overlayAuxLines runs on the already
// gamma-encoded colour), so a partially transparent line lands on different bytes even where it
// covers exactly the same pixels. Measured on full_sky_dual_fisheye at alpha 0.3 over its
// background: 129 vs 160 per channel on a line pixel, which matches the two formulas to within a
// count and costs 2.9 dB of whole-frame PSNR. At alpha 1 the background term drops out of both and
// they agree exactly. The divergence is older than the grid — it applies to the circles and the
// horizon too — and belongs to whoever unifies the two compositors; pinning it here would only
// bury this gate's actual subject, which is WHERE the curves land.
//
// "n/a" means the break does not move that scene, and in every case for a stated reason rather
// than a gap: the full-sky lens family ignores fov and zeroes the three view angles, so a break in
// those cannot show there; `visible` and `lens_type` are broken TO the value that scene already
// holds; and the horizon cell is discussed below. Each field is therefore live in at least one
// column, and the two columns between them cover both sides of every branch the export arm has —
// single lens vs the full-sky family, an aspect preset that names a ratio vs the two that name
// none and fall back to 2:1 — rather than nine unrelated checkmarks.
//
// The `resolution` break is the one that does not report as a PSNR drop: the canvas assertion in
// TestFunc fires first, because a wrong canvas is a finding in its own right and is worth saying
// as itself. That is deliberate; do not "fix" it into a PSNR comparison by resizing.
//
// ================================= Deliberately not covered ==================================
//
//   * The lens border, which remains a GUI display-time layer with no encoding in the config
//     format, so there is still nothing on the CLI side to compare against. Off in both scenes,
//     which is also its default.
//   * The TEXT LABELS, and this one is now an exclusion with a reason rather than a gap. As of
//     v4.21 they ARE encoded (grid.horizon_label / grid.label / grid.angular_dist_label) and the
//     CLI does draw them, from the same core anchors the GUI reads — so the placement half of
//     "what the GUI shows is what the export renders" is already covered by the curves those
//     anchors sit on. What is NOT comparable is the GLYPHS: the GUI rasterizes through ImGui's
//     font atlas and its draw list, core through stb_truetype into the image buffer, and the two
//     also differ in what they do around a label — the GUI clamps a label inside the viewport and
//     drops one that collides with another, the CLI draws every anchor where core put it. Both
//     halves are deliberate (see src/core/annotation_font.hpp and the CLI-side notes in
//     server/render.cpp), so a pixel comparison here would pin two rasterizers against each other,
//     which is not this gate's subject. All three switches are off in both scenes, which is also
//     their default.
//
//     The sun circles USED to be on this list, with the note "re-add coverage here the day core
//     gains an annotation layer". That day came, and the altitude grid followed it: both are now on
//     in both scenes, and both are overlays whose two arms are not two implementations. Each builds
//     its geometry from the same core call (LUMICE_ComputeAnnotationOverlay), the CLI once per line
//     in server/render.cpp and the GUI once per settled view in gui/annotation_overlay_cache.cpp.
//     That is why turning either ON RAISES both scenes' PSNR rather than lowering it — the curves
//     land on identical pixels, so where the two frames used to differ they now agree. A drop is
//     therefore the signal, and the thresholds below are set against the measured breaks.
//
//     The zenith/nadir markers left the list the same way and are on in both scenes, but they are
//     the member that does NOT raise the figure: measured at the default radius, switching them on
//     costs the full-sky scene 0.08 dB and leaves the single-lens scene where it was. Both arms put
//     the ring in the same place — that is core's one answer, read twice — and what the 0.08 dB
//     buys is the difference between an antialiased ring edge and a hard one. It is a fixed,
//     understood cost carried on purpose so the export path runs end to end here; see the
//     zenith_nadir row in the field table for why the alternative (a ring big enough for the metric
//     to see) was measured and rejected.
//   * The colour space an overlay line is composited in, which the two arms genuinely disagree
//     about. Measured, excluded on purpose, and neutralised rather than tolerated — see the
//     GRID OPACITY note above the field table for the numbers and the mechanism.
//   * The horizon in its ON state, and this one is a measured exclusion rather than an assumed
//     one. Both scenes keep the switch OFF, so what this fixture pins is the direction that
//     actually regressed before: the export must not assert a horizon line the user switched off
//     (it once wrote the INVERSE of the switch). Turning the switch on is not usable as a probe,
//     because the two renderers do not draw the same line: measured on the full-sky scene,
//     enabling it on both sides costs 1.61 dB, of which turning the CLI's line back off recovers
//     1.43 dB — i.e. nearly all of the mismatch is core's line landing where the GUI's is not.
//     The GUI's is a shader line whose width comes from fwidth() of the altitude field
//     (preview_renderer.cpp overlayAuxLines), core's a mask built at a fixed pixel width
//     (server/render.cpp BuildHorizonMask); on a dual-fisheye frame those two widths part company
//     near the circle rim. Making them agree is the annotation layer's business, not this gate's.
//   * The single-lens fisheye domain past theta = 90 degrees. This USED to be a real and large
//     exclusion — the preview shader kept inverting toward the frame corners while core stopped at
//     the equator, and a 4:3 frame at fov 150 measured 25% of its pixels lit by the GUI and black
//     in the CLI. That gap was closed in 474.1 (core's cull is now per lens type and runs to
//     theta = 180 deg for equal-area and equidistant), and the pixel-for-pixel comparison of the
//     two domains lives where it can be made cheaply and exhaustively: the unit-level mask gate
//     test/unit-correctness/gui/test_visible_mask_gui_parity.cpp. It stays off this fixture's list
//     not because it diverges but because this fixture compares RENDERED energy on a scene whose
//     fov keeps the whole frame well inside both domains; widening its fov to exercise the rim
//     would buy a duplicate of that unit gate at the cost of a much noisier oracle.
//   * A loaded background IMAGE (GuiState::bg_*). Owner-decided GUI-only: it is never exported, so
//     there is no honest comparison to make. Neither scene loads one.
//   * RenderConfig::ray_color. The GUI's tint control does not reach the renderer, and the export
//     writes core's "use the natural spectral colour" sentinel; there is no divergence to detect.
//   * RenderConfig::front (the front-hemisphere clip). It IS exported now — core gained the field
//     and the old refusal is gone — so this is a genuine gap rather than a structural one, and it
//     is left open deliberately. What the clip needs proved is that core's mask and the shader cut
//     the same pixels, and that is already pinned exactly, per pixel, by
//     test_visible_mask_gui_parity.cpp's FrontClipMatchesTheGuiRule, which compares the two
//     implementations directly instead of comparing two rendered images of them. A scene here would
//     re-ask the same question through a noisier instrument (a child CLI process and a PSNR floor).
//     Add one if the clip ever acquires behaviour beyond the mask — a ray-level cull, say.
//   * lens_shift. The GUI exposes no control for it, so there is no user-visible value the export
//     could be dishonest about.
//   * The exposure anchor. See the note above kScenes[]: both scenes pin relative EV, and what is
//     left over after that is a measured, stated residual rather than an evasion.
//
// ====================================== Platform reach =======================================
//
// Do not read a green CI as a green here. gui_test is COMPILED on macOS, Windows and Linux but RUN
// by exactly one CI leg (.github/workflows/ci.yml, Ubuntu x86_64 under xvfb-run with Mesa
// llvmpipe), and that leg passes a hand-picked positive filter naming only two reference groups.
// This category is not in it, in company with most of this binary's categories, so today NO CI job
// executes this fixture. The two pytest legs build with -DBUILD_GUI=OFF and do not have the binary
// at all. Where it does run is a developer machine with a working GL context: scripts/build.sh's
// correctness pool selects tests by a NEGATIVE filter, so this category is included by default,
// and ./scripts/test.sh {quick,full,pr} therefore executes it.
//
// This is also the first place in the repo where a test binary starts the CLI binary as a child
// process. See RunCliRender below for the mechanics and for what that costs in portability.

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

#include "gui/gui_constants.hpp"
#include "include/lumice.h"
#include "test_gui_shared.hpp"

namespace {

struct ParityScene {
  const char* name;
  // Renderer fields, applied on top of the loaded document.
  int lens_type;
  float fov;
  float azimuth;
  float elevation;
  float roll;
  int visible;
  float background_srgb[3];
  // Display-group framing.
  gui::AspectPreset aspect_preset;
  bool aspect_portrait;
  // The one overlay core can also draw. Off in both scenes; see the header's exclusion note.
  bool show_horizon;
  // Angular-distance circles. ON in both scenes, unlike the horizon, because these two arms are
  // not two implementations of the same curve — they are two readings of one. See the exclusion
  // note above for why that makes turning them on raise the PSNR rather than lower it.
  bool show_sun_circles;
  // The coordinate grid, on in both scenes for the same reason the circles are: since this task
  // both arms build it from one core call, so it is two readings of one curve rather than two
  // implementations. See the exclusion note above.
  bool show_grid;
  // The zenith / nadir ring markers, on in both scenes and the newest member of the "two readings
  // of one call" family: both arms take the two points from LUMICE_ComputeAnnotationOverlay and
  // draw a ring of the config's radius around each. Unlike the three line families this one is a
  // PAIR, and the two halves are independent — which is what the single-sided break below tests.
  bool show_zenith_nadir;
  // Ray budget, in millions. Must be a dyadic fraction so ExpectedSimRayNum's truncation and
  // rounding agree — see its note in test_gui_shared.hpp.
  float ray_num_millions;
  double psnr_threshold;
  // What the export arm must compute for the canvas, asserted before the images are compared so a
  // size disagreement is reported as itself rather than as a PSNR failure.
  int expect_w;
  int expect_h;
};

// Both scenes share one document (test/e2e/configs/halo_22.json: prism crystals, sun at 20
// degrees) and differ only in how it is framed, so a PSNR drop localizes to the framing rather
// than to the scene.
//
// EXPOSURE. Both scenes pin relative EV, overriding the absolute the document asks for, and that
// is a statement about what absolute mode promises rather than a convenience. Absolute mode
// anchors on emitted energy and normalizes by the frame's own pixel COUNT
// (src/server/render.cpp ExposureScale, src/gui/mono_exposure_scale.hpp), so the brightness it
// produces is a function of the canvas and the lens. The GUI preview's pixels come from the
// full-sky simulation texture and are scaled by THAT texture's pixel count; the CLI renders the
// scene's own lens directly into the exported canvas and scales by its. The two therefore differ
// by a fixed factor whenever the exported canvas is not the simulation texture's own shape —
// which is the "comparable only at equal lens / FOV / resolution" boundary
// doc/ev-pipeline-architecture.md states for absolute mode, not a defect for this fixture to
// report. Relative mode has no such term: both sides self-anchor on their own frame.
//
// What relative mode leaves behind is a residual, and it is stated rather than hidden: the two
// anchors are P99 over DIFFERENT pixel populations (the GUI's over the whole simulation texture,
// the CLI's over the framed view), so a narrow frame reads brighter on the GUI side. Measured on
// the single-lens scene as the mean ratio over lit pixels: 1.36 at fov 60, 1.21 at fov 96, 1.13 at
// fov 150 — monotone in how much sky the frame holds. It costs this scene absolute PSNR, and
// nothing else: it is stable run to run (sigma below), so it lowers the operating point without
// touching the gate's ability to see a field break, which the table above measures directly.
//
// PROJECTION FAMILY. Two of the three scenes use an EQUAL-AREA projection and the third does not,
// and the split is load-bearing in both directions. The CLI renders its lens directly, so each
// pixel accumulates energy over its own solid angle and the projection's Jacobian is baked into
// the image; the GUI resamples an equal-area texture, where every texel subtends the same solid
// angle. For an equal-area lens the target Jacobian is spatially constant and the two agree up to
// a constant whatever the shader does. For anything else they do not agree unless the shader
// applies the target lens's RELATIVE ILLUMINATION — its per-pixel solid angle normalized to the
// on-axis one. Before that factor existed, a rectilinear scene measured a GUI/CLI brightness ratio
// of 0.79 at frame centre against 1.35 at the edges — the cos^3 natural vignetting of that
// projection, present on one side only. `single_lens_rectilinear` below is the scene that turns
// that into a red, and it
// is why the two equal-area scenes are no longer the whole story: they cannot see the factor at all
// (their relative illumination is identically 1), so on their own they would let it be deleted.
//
// SINGLE-LENS FOV BOUND. The single-lens EQUAL-AREA scene sits at fov 96, and the reason has
// changed even though the number has not. It was originally the largest fov whose frame corner
// stayed inside core's old theta <= 90 deg domain: on a 4:3 frame the corner sits at 1.665 image
// radii, so sin(theta_c/2) = 1.665 * sin(fov/4) and theta_c <= 90 deg needs fov <= 100. Core's
// domain now reaches theta = 180 deg for this lens (474.1), so that ceiling is gone — the same
// corner stays inside the domain out to fov = 360. What keeps the scene at 96 now is that this is
// a PSNR fixture, not a domain fixture: at 96 the two sides agreed to zero pixels before the
// widening and still do, which is the quiet baseline the field-by-field breaks below are measured
// against. Raising the fov would move this scene onto the rim, where the two paths' sampling
// differs for reasons that have nothing to do with the fields under test.
//
// That ceiling never bound the RECTILINEAR scene, and for a structural reason rather than a lucky
// number: that projection maps the image radius through theta = atan(rho / focal), which is
// strictly below 90 degrees at every finite radius. There is no image circle to invert past, so no
// fov below 180 can put the corner outside the shared domain. Re-derive this if the lens is ever
// changed; do not carry the sentence over.
//
// THRESHOLDS. Calibrated, not chosen: N=12 full runs of this category on an otherwise idle
// machine, per-scene mean and population sigma recorded on each row. Sigma is an order of
// magnitude smaller than the visual-regression suites' because neither side of this comparison is
// a committed asset — both images are produced in the same run from a ray budget fixed by waiting
// for the run to COMPLETE, so machine load cannot leak into the noise level the way it can when a
// capture is taken on a counter threshold. Each threshold is placed in the gap between the worst
// honest run and the smallest break that scene must catch, at least 10 sigma below the mean.
// clang-format off
const ParityScene kScenes[] = {
  // mean 27.058 sigma 0.1064 (N=6, range 26.92-27.24). Threshold 26.0: 9.9 sigma below the mean and
  // 0.27 dB above the smallest break this scene is asked to catch — the CLI drawing only the first
  // of two angular_dist lines, at 25.73 dB. A dropped MERIDIAN, at 26.59 dB, is deliberately NOT
  // among them: catching it here would need a threshold within 3 sigma of the mean, and its
  // neighbour catches the same break at 3.5 dB of margin. See the grid rows in the field table.
  //
  // RECALIBRATED when the coordinate grid was switched on, which raised the mean by 0.37 dB and
  // very nearly doubled sigma (0.0668 -> 0.1064) — the grid's saturated pixels are a larger share
  // of the frame than the circles' were, so a given amount of per-run noise moves the whole-frame
  // figure further. The threshold is unchanged because the mean moved AWAY from it. If this row
  // ever flakes, re-measure at N=12 rather than nudging the threshold — 6 samples is enough to
  // place a 10 sigma gate and not enough to argue about a 2 sigma one.
  //
  // RE-MEASURED when the zenith/nadir markers were switched on: mean 26.962 sigma 0.0858 (N=4,
  // range 26.83-27.06), i.e. this scene's single ring is inside its own noise. Threshold unchanged
  // at 26.0, now 11.2 sigma below the mean.
  {"single_lens_angled",
   lumice::gui::kLensTypeFisheyeEqualArea, 96.0f, 25.0f, 30.0f, 15.0f, lumice::gui::kVisibleUpper,
   /*background_srgb=*/{ 0.10f, 0.16f, 0.28f },
   gui::AspectPreset::k4x3, /*aspect_portrait=*/true, /*show_horizon=*/false, /*show_sun_circles=*/true,
   /*show_grid=*/true, /*show_zenith_nadir=*/true,
   /*ray_num_millions=*/16.0f, /*psnr_threshold=*/26.0, /*expect_w=*/512, /*expect_h=*/683},
  // mean 27.602 sigma 0.0157 (N=6, range 27.58-27.62). Threshold 27.2: 25 sigma below the mean and
  // 0.31 dB above the smallest break this scene owns — the CLI drawing only the first of two
  // angular_dist lines, at 26.89 dB. Raised from 27.0 when the grid was switched on: the mean moved
  // up 0.25 dB and the circle break moved with it, so leaving the threshold where it was would have
  // left only 0.11 dB between the gate and the break it exists to catch.
  //
  // Same recalibration caveat as its neighbour: N=6, on a mean that moved. Do not read the small
  // sigma as a licence to run this tighter than 27.2 — the binding constraint on this row is the
  // break below it, not the noise above it.
  //
  // RE-MEASURED when the zenith/nadir markers were switched on: mean 27.518 sigma 0.0268 (N=4,
  // range 27.49-27.56), 0.08 dB BELOW the markers-off mean of 27.602 measured in the same session.
  // That drop is the two rings' antialiased-vs-hard edge and is carried on purpose — see the
  // zenith_nadir row in the field table. Threshold unchanged at 27.2: still 11.8 sigma below the
  // mean, and still above the smallest break this scene owns, which moved down by the same 0.08.
  {"full_sky_dual_fisheye",
   lumice::gui::kLensTypeDualFisheyeEqualArea, 180.0f, 25.0f, 30.0f, 15.0f, lumice::gui::kVisibleFull,
   /*background_srgb=*/{ 0.28f, 0.14f, 0.10f },
   gui::AspectPreset::kFree, /*aspect_portrait=*/false, /*show_horizon=*/false, /*show_sun_circles=*/true,
   /*show_grid=*/true, /*show_zenith_nadir=*/true,
   /*ray_num_millions=*/16.0f, /*psnr_threshold=*/27.2, /*expect_w=*/1024, /*expect_h=*/512},
  // The projection-family scene. Every field except lens_type and fov is copied verbatim from
  // single_lens_angled, so the difference between the two rows is the projection and nothing else
  // — which is what makes a drop here readable as the Jacobian rather than as some other field.
  //
  // fov 120 rather than the 160 the original measurement used. Both are inside the shared domain
  // (see the note above), and both show the effect; 120 was chosen because it puts the frame
  // corner at theta = 70.9 degrees, where the cos^3 relative illumination is 0.035 — a 28x
  // corner-to-centre spread, decisive as a red without pushing the corners so far into the
  // grazing region that the comparison is dominated by resampling the source texture's equator.
  //
  // mean 33.157 sigma 0.1400 (N=13, range 32.83-33.34). Threshold 31.5 = mean - 1.66 dB = 12
  // sigma, and 1.33 dB below the worst honest run. Placed well below mean - 1.0 dB, and not by
  // preference: this scene's sigma is the largest of the three, and the note above requires at
  // least 10 sigma, which 32.0 (9.3 sigma once the thirteenth sample widened the spread) did not
  // reach. It costs nothing to give it, because the break this row exists to catch is enormous:
  // with the relative-illumination factor absent from the shader — the state the row was landed
  // in and measured at — it reads 26.44, 26.40 and 26.28 dB, 5.2 dB below this threshold.
  {"single_lens_rectilinear",
   lumice::gui::kLensTypeLinear, 120.0f, 25.0f, 30.0f, 15.0f, lumice::gui::kVisibleUpper,
   /*background_srgb=*/{ 0.10f, 0.16f, 0.28f },
   gui::AspectPreset::k4x3, /*aspect_portrait=*/true, /*show_horizon=*/false, /*show_sun_circles=*/false,
   /*show_grid=*/false,
   /*ray_num_millions=*/16.0f, /*psnr_threshold=*/31.5, /*expect_w=*/512, /*expect_h=*/683},
};
// clang-format on
// 512 -> a 1024x512 dual-equal-area simulation texture, the smallest this suite offers. Both the
// export canvas and the GUI capture derive from it, so it fixes the working point the thresholds
// above were calibrated at; changing it invalidates them.
constexpr int kSimResolutionIndex = 0;
constexpr int kSceneCount = sizeof(kScenes) / sizeof(kScenes[0]);

// Same shape and same reason as the guard in test/gui/visual/test_gui_lens_projection.cpp: every
// IM_CHECK* below can return early, and only a destructor tears down a running server and restores
// a widened watchdog on that path.
struct ScopedServerAndWatchdogGuard {
  ImGuiTestEngineIO* engine_io;
  float saved_watchdog_warn;
  float saved_watchdog_kill;
  bool server_owned = true;

  explicit ScopedServerAndWatchdogGuard(ImGuiTestEngineIO* io)
      : engine_io(io), saved_watchdog_warn(io->ConfigWatchdogWarning), saved_watchdog_kill(io->ConfigWatchdogKillTest) {
  }

  ~ScopedServerAndWatchdogGuard() {
    engine_io->ConfigWatchdogWarning = saved_watchdog_warn;
    engine_io->ConfigWatchdogKillTest = saved_watchdog_kill;
    if (server_owned && gui::g_server != nullptr) {
      gui::g_server_poller.Stop();
      LUMICE_StopServer(gui::g_server);
      LUMICE_DestroyServer(gui::g_server);
      gui::g_server = nullptr;
      gui::g_state.run_intent = gui::RunIntent::kNone;
    }
  }
};

// The canvas and the renderer id the exported config asks for. Parsed rather than recomputed: the
// canvas the GUI capture is taken at has to come from the export itself, or the comparison would
// be between two pictures that agreed only because the test computed the same number twice.
struct ExportedRenderInfo {
  int width = 0;
  int height = 0;
  int renderer_id = -1;
  // Whether the exported document asks the CLI for the zenith / nadir markers at all. Read from
  // the document rather than from GuiState because that is what the child process will read.
  bool zenith_nadir = false;
  bool ok = false;
};

ExportedRenderInfo ParseExportedRenderInfo(const std::string& json_str) {
  ExportedRenderInfo info;
  nlohmann::json root = nlohmann::json::parse(json_str, nullptr, /*allow_exceptions=*/false);
  if (root.is_discarded() || !root.contains("render") || !root["render"].is_array() || root["render"].empty()) {
    return info;
  }
  const auto& jr = root["render"][0];
  if (!jr.contains("resolution") || !jr["resolution"].is_array() || jr["resolution"].size() != 2) {
    return info;
  }
  info.width = jr["resolution"][0].get<int>();
  info.height = jr["resolution"][1].get<int>();
  info.renderer_id = jr.value("id", 0);
  if (jr.contains("grid") && jr["grid"].contains("zenith_nadir")) {
    info.zenith_nadir = jr["grid"]["zenith_nadir"].value("enabled", false);
  }
  info.ok = info.width > 0 && info.height > 0;
  return info;
}

// Run the CLI binary on `config_path`, writing into `out_dir`.
//
// std::system, not a spawn API: this is the only child process in the test tree, and the two
// platform families it has to work on both hand the string to a shell that treats a double-quoted
// argument the same way. Every path is quoted because this repository is routinely checked out
// under a directory with a space in it. The command line is echoed to stderr on failure, which is
// what makes a failure reproducible by hand; test/ is outside the scope of the no-bare-print gate
// for exactly this kind of harness diagnostic.
//
// LUMICE_CLI_BIN_PATH is a generator expression resolved at configure time
// (test/gui/CMakeLists.txt). A generator expression is only a string, so that file also declares a
// build dependency on the CLI target — without it, this would happily run whatever binary happened
// to be left over from a previous build, or none.
bool RunCliRender(const std::string& config_path, const std::string& out_dir) {
  const std::string cmd = "\"" LUMICE_CLI_BIN_PATH "\" -f \"" + config_path + "\" -o \"" + out_dir + "\" --format png";
  const int rc = std::system(cmd.c_str());
  if (rc != 0) {
    fprintf(stderr, "[export_parity] CLI render failed (rc=%d): %s\n", rc, cmd.c_str());
    return false;
  }
  return true;
}

}  // namespace

void RegisterExportParityTests(ImGuiTestEngine* engine) {
  for (int idx = 0; idx < kSceneCount; idx++) {
    ImGuiTest* t = IM_REGISTER_TEST(engine, "export_parity", kScenes[idx].name);
    t->ArgVariant = idx;
    t->TestFunc = [](ImGuiTestContext* ctx) {
      const auto& scene = kScenes[ctx->Test->ArgVariant];
      ResetTestState();

      gui::g_server = LUMICE_CreateServer();
      ScopedServerAndWatchdogGuard guard(ctx->EngineIO);
      LUMICE_SetLogLevel(gui::g_server, static_cast<LUMICE_LogLevel>(g_core_log_level));

      // 1. Load the document exactly as the product does when a .json is opened
      // (src/gui/app.cpp DoOpen -> DeserializeFromJson, which resets GuiState internally).
      {
        std::ifstream in(LUMICE_E2E_CONFIG_DIR "/halo_22.json");
        IM_CHECK(in.is_open());
        const std::string json_str((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
        IM_CHECK(gui::DeserializeFromJson(json_str, gui::g_state));
      }

      // 2. Apply the scene. These are writes to GuiState only — no PreviewParams is touched here,
      // because the whole point is to let the production per-frame assembly do that translation.
      {
        auto& rc = gui::g_state.renderer;
        rc.lens_type = scene.lens_type;
        rc.fov = scene.fov;
        rc.azimuth = scene.azimuth;
        rc.elevation = scene.elevation;
        rc.roll = scene.roll;
        rc.visible = scene.visible;
        rc.front = false;
        rc.ev_mode = 0;  // relative; see the exposure note above kScenes[]
        rc.exposure_offset = 0.0f;
        std::copy(std::begin(scene.background_srgb), std::end(scene.background_srgb), std::begin(rc.background));
        rc.sim_resolution_index = kSimResolutionIndex;
      }
      gui::g_state.aspect_preset = scene.aspect_preset;
      gui::g_state.aspect_portrait = scene.aspect_portrait;
      gui::g_state.show_horizon_line = scene.show_horizon;
      gui::g_state.show_sun_circles_line = scene.show_sun_circles;
      gui::g_state.show_grid_line = scene.show_grid;
      gui::g_state.show_zenith_nadir_line = scene.show_zenith_nadir;
      // FULL OPACITY, deliberately, and not the 0.3 a user gets. The two arms composite an overlay
      // line in different colour spaces — the CLI blends it into radiance before the transfer curve
      // (server/render.cpp PostSnapshot), the preview shader after it (overlayAuxLines runs on the
      // already-gamma-encoded colour) — so a partially transparent line lands on different bytes on
      // the two sides even when it covers the same pixels. Measured on this scene at alpha 0.3 over
      // its background: 129 vs 160 per channel, 2.7 dB off the whole-frame PSNR. At alpha 1 the
      // background term drops out of both formulas and they agree exactly, which is what lets this
      // gate measure WHERE the curves land — the thing this task changed — instead of re-measuring
      // a divergence it did not introduce and does not fix. See the exclusion note in the header.
      gui::g_state.grid_alpha = 1.0f;
      // The markers take the same override for the same reason, and they need it more than the
      // lines do: a ring is a handful of pixels, so a per-pixel byte difference on every one of
      // them is most of what the marker contributes to the frame at all.
      gui::g_state.zenith_nadir_alpha = 1.0f;
      // The default list, {22, 46}, is what a user gets; keeping it means this scene compares the
      // circles anyone would actually draw.
      gui::g_state.sun_circle_angles = { 22.0f, 46.0f };
      gui::g_state.sim.infinite = false;
      gui::g_state.sim.ray_num_millions = scene.ray_num_millions;

      // 3. Run to completion. kDone means the backend reported the committed epoch complete, so the
      // capture below is taken on a fixed amount of work rather than on whatever a poll happened to
      // pick up. The wall-clock deadline (and the watchdog raised out of its way) is the same
      // arrangement the lens-projection suite arrived at: under --fixed-dt the engine's watchdog
      // measures SIMULATED time and can fire while a real-time budget still has minutes left.
      gui::DoRun(/*user_initiated=*/true);
      IM_CHECK_EQ((int)gui::g_state.run_intent, (int)gui::RunIntent::kRunning);
      guard.engine_io->ConfigWatchdogWarning = 50000.0f;
      guard.engine_io->ConfigWatchdogKillTest = 100000.0f;
      const auto wait_deadline = std::chrono::steady_clock::now() + std::chrono::seconds(170);
      while (gui::g_state.sim_state != gui::GuiState::SimState::kDone &&
             std::chrono::steady_clock::now() < wait_deadline) {
        ctx->Yield(1);
      }
      IM_CHECK_EQ((int)gui::g_state.sim_state, (int)gui::GuiState::SimState::kDone);
      IM_CHECK_EQ((unsigned long long)gui::g_state.stats_sim_ray_num, ExpectedSimRayNum(scene.ray_num_millions));

      // 4. Let the product's own per-frame assembly fill g_preview_vp.params from GuiState. This is
      // the step that makes the GUI side of this comparison the real one: src/gui/app_panels.cpp
      // reads lens/fov/view/visible/background/horizon out of GuiState every frame, and it is that
      // translation — not a hand-written copy of it — that has to agree with the export.
      //
      // Asserted, not assumed: the assembly is gated on the preview owning a texture, so "the
      // frames went by" is not evidence it ran.
      ctx->Yield(3);
      IM_CHECK(gui::g_preview.HasTexture());
      IM_CHECK(gui::g_preview_vp.active);
      // The full-sky branch of that same assembly zeroes the three view angles. Reading it back
      // here states which side of the branch this scene is on before anything is rendered.
      if (gui::LensIsFullSky(scene.lens_type)) {
        IM_CHECK_EQ(gui::g_state.renderer.elevation, 0.0f);
        IM_CHECK_EQ(gui::g_state.renderer.azimuth, 0.0f);
        IM_CHECK_EQ(gui::g_state.renderer.roll, 0.0f);
      } else {
        IM_CHECK_EQ(gui::g_state.renderer.elevation, scene.elevation);
      }

      // 5. The export, through the production builder. A scene that reaches this point must not be
      // one the builder refuses (only the front-hemisphere clip is refused, and no scene sets it).
      std::string export_json;
      std::string warning;
      IM_CHECK(gui::BuildExportJsonOrWarn(gui::g_state, &export_json, &warning));
      const ExportedRenderInfo info = ParseExportedRenderInfo(export_json);
      IM_CHECK(info.ok);
      IM_CHECK_EQ(info.width, scene.expect_w);
      IM_CHECK_EQ(info.height, scene.expect_h);
      IM_CHECK_EQ(info.zenith_nadir, scene.show_zenith_nadir);

      const std::filesystem::path scratch_dir =
          GuiTestTempPath(std::string("export_parity_") + scene.name).parent_path() /
          (std::string("export_parity_") + scene.name);
      std::error_code ec;
      std::filesystem::create_directories(scratch_dir, ec);
      IM_CHECK(!ec);
      const std::filesystem::path json_path = scratch_dir / "export.json";
      {
        std::ofstream out(json_path);
        IM_CHECK(out.is_open());
        out << export_json;
      }

      // 6. The GUI image, at the canvas the export just asked for. The params are the ones the
      // product assembled; only the output size is imposed, and it is imposed from the export so
      // both pictures land on the same pixel grid.
      gui::PreviewViewport vp = gui::g_preview_vp;
      vp.vp_w = info.width;
      vp.vp_h = info.height;
      // The fixture checks itself before it compares anything. g_preview_vp is filled by
      // RenderPreviewPanel on whatever frame it last ran, so everything below is a statement that
      // the picture about to be captured is being taken in the state this test asked for — not in
      // an earlier test's, and not with an annotation silently switched off. Without these, a
      // scene that quietly lost half its setup still produces two images and a plausible PSNR, and
      // the number moves for a reason no one can attribute. Measured worth: this suite read 2.4 dB
      // lower under the full-suite invocation than under --filter, and it was these values that
      // said which of the two arms had drifted.
      IM_CHECK_EQ(vp.params.overlay.show_sun_circles, scene.show_sun_circles);
      IM_CHECK_EQ(vp.params.overlay.show_grid, scene.show_grid);
      IM_CHECK_EQ(vp.params.overlay.show_zenith_nadir, scene.show_zenith_nadir);
      IM_CHECK_EQ(vp.params.overlay.grid_alpha, 1.0f);
      IM_CHECK_EQ(vp.params.overlay.zenith_nadir_alpha, 1.0f);
      IM_CHECK_EQ(vp.params.overlay.sun_circles_alpha, gui::g_state.sun_circles_alpha);
      if (scene.show_sun_circles) {
        IM_CHECK(vp.params.overlay.angular_dist_mask != nullptr);
      }
      if (scene.show_grid) {
        IM_CHECK(vp.params.overlay.grid_mask != nullptr);
      }
      const std::string gui_png = (scratch_dir / "gui.png").string();
      IM_CHECK(RequestAndWaitPreviewExport(ctx, vp, gui_png));

      // 7. Stop the server before handing the machine to the child process: the CLI is about to
      // want every core it can get, and nothing below needs the server.
      guard.server_owned = false;
      gui::g_server_poller.Stop();
      LUMICE_StopServer(gui::g_server);
      LUMICE_DestroyServer(gui::g_server);
      gui::g_server = nullptr;
      gui::g_state.run_intent = gui::RunIntent::kNone;

      // 8. The CLI image. The filename carries the renderer id the exported document states, not a
      // hardcoded 0 — src/main.cpp names its output after that id.
      IM_CHECK(RunCliRender(json_path.string(), scratch_dir.string()));
      char cli_name[32];
      snprintf(cli_name, sizeof(cli_name), "img_%02d.png", info.renderer_id);
      const std::string cli_png = (scratch_dir / cli_name).string();

      // 9. Compare. A size disagreement is a finding in its own right and is reported as one
      // rather than absorbed by a resize.
      std::vector<unsigned char> gui_data;
      std::vector<unsigned char> cli_data;
      int gw = 0;
      int gh = 0;
      int gc = 0;
      int cw = 0;
      int ch = 0;
      int cc = 0;
      IM_CHECK(lumice::test::LoadPng(gui_png.c_str(), gui_data, gw, gh, gc));
      IM_CHECK(lumice::test::LoadPng(cli_png.c_str(), cli_data, cw, ch, cc));
      IM_CHECK_EQ(gw, cw);
      IM_CHECK_EQ(gh, ch);
      // The CLI's PNG writer emits RGB, never RGBA, so cc==3 is a format contract, not an
      // assumption this fixture happens to get away with; if that writer ever gains an alpha
      // channel this assertion is the thing that should tell you, not a silent 3-vs-4 mismatch.
      IM_CHECK_EQ(cc, 3);
      std::vector<unsigned char> gui_rgb = gc == 4 ? lumice::test::StripAlpha(gui_data.data(), gw, gh) : gui_data;
      const double psnr = lumice::test::ComputePsnr(gui_rgb.data(), cli_data.data(), gw, gh, 3);
      // Same "[<group>] <tag>: PSNR=" spelling every other pixel comparison in this binary prints,
      // so one grep finds them all. Deliberately not routed through CheckAgainstReference: that
      // function's subject is a committed reference file, which this suite does not have.
      fprintf(stderr, "[export_parity] %s: PSNR=%.2f dB (threshold=%.1f dB) size=%dx%d\n", scene.name, psnr,
              scene.psnr_threshold, gw, gh);
      IM_CHECK_GE(psnr, scene.psnr_threshold);

      if (!g_keep_export_png) {
        std::filesystem::remove_all(scratch_dir, ec);
      }
    };
  }
}
