// CLI<->GUI export parity — the gate that makes "what the GUI shows is what the exported config
// renders" a proposition something can turn red on.
//
// The proposition. A document is loaded in the GUI, a scene's view settings are applied, the run
// completes, and two images are produced from that one document:
//   (1) the GUI side, through the SAME per-frame PreviewParams assembly the product uses
//       (src/gui/app_panels.cpp fills g_preview_vp.params from GuiState every frame) rendered
//       off-screen by gui::ExportPreviewPng;
//   (2) the CLI side, by handing gui::BuildExportJsonOrWarn's output to the Lumice CLI binary in
//       a child process and reading the image it writes.
// The two are compared by PSNR. Nothing here re-encodes a field by hand: both sides come out of
// production functions, which is the point — a fixture that rebuilt the export JSON itself would
// be a second mirror of the very code under test.
//
// Why a category of its own, in a directory of its own. Everything under test/gui/visual/ compares
// a capture against a COMMITTED reference image and is therefore regenerated by
// scripts/regen_gui_test_refs.py's GROUPS registry. This suite compares two renders made in the
// same run; it owns no committed asset and must never be added to that registry. The directory
// boundary says so structurally, so a contributor does not have to read this comment to find out.
//
// What it does NOT subsume. Three sibling comparisons stay where they are, because each answers a
// different proposition:
//   * test/e2e-correctness/test_ev_mode_relative_gui_parity.py compares the CLI's baked image
//     against the GUI's exposure FORMULA re-run over the same buffer through the C API. No GUI
//     process, no shader; its own docstring records that it strips the scene down to exposure
//     alone precisely because background / ray_color / grid / outline are baked by the CLI and
//     not by LUMICE_XyzToSrgbUint8.
//   * test/unit-correctness/gui/test_visible_mask_gui_parity.cpp and
//     test/unit-correctness/gui/test_horizon_gui_parity.cpp compare core's C++ predicate against a
//     CPU mirror of the GLSL one. They answer the SHAPE of the disagreement (which pixels, and on
//     which side of which boundary) — something a whole-image PSNR cannot express — and they need
//     no display, so they run on every platform. Complementary, not duplicated.
//
// Field coverage (the fields src/gui/file_io.cpp's BuildScene fills only on its kJsonExport arm):
//
//   field           | single_lens_angled            | full_sky_dual_fisheye
//   ----------------|------------------------------|-----------------------------------
//   lens_type       | fisheye_equal_area (single)  | dual_fisheye_equal_area (full-sky)
//   lens_fov        | 150 (non-default)            | 180
//   visible         | upper                        | full
//   view_azimuth    | 25 (applied)                 | forced to 0 by the full-sky branch
//   view_elevation  | 30 (applied)                 | forced to 0 by the full-sky branch
//   view_roll       | 15 (applied)                 | forced to 0 by the full-sky branch
//   background      | non-black                    | a different non-black
//   resolution      | 4:3 + portrait -> 512x683    | no ratio named -> 2:1 fallback
//   horizon         | on                           | off
//
// Every field appears in both columns, so the table is a BRANCH matrix rather than a checklist:
// the two rows exercise the two sides of each branch the export arm has (single lens vs the
// full-sky lens family whose view angles src/gui/app_panels.cpp zeroes; an aspect preset that
// names a ratio vs the two that name none and fall back to 2:1; horizon on vs off).
//
// Deliberately outside this fixture, each for a stated reason rather than by omission:
//   * The auxiliary-line overlay other than the horizon (altitude grid, sun circles, zenith/nadir
//     markers, lens border, text labels). These are GUI display-time layers with no encoding in
//     the config format at all; giving core an annotation layer is a separate design effort, and
//     until it exists there is nothing on the CLI side to compare against. All of them are off in
//     both scenes, which is also their default.
//   * The single-lens fisheye domain past theta = 90 degrees, where the preview shader and core
//     disagree about which directions the lens still images. That divergence is being widened on
//     purpose elsewhere; pinning it here would freeze the shape that is about to change. Both
//     scenes stay inside the agreed domain.
//   * A loaded background IMAGE (GuiState::bg_*). Owner-decided GUI-only: it is never exported, so
//     there is no honest comparison to make. Neither scene loads one.
//   * RenderConfig::ray_color. The GUI's tint control does not reach the renderer, and the export
//     writes core's "use the natural spectral colour" sentinel; there is no divergence to detect.
//   * RenderConfig::front (the front-hemisphere clip). BuildExportJsonOrWarn REFUSES to export a
//     document with it set, so that path produces no config and therefore no second image. Its
//     test is the refusal itself, which lives with the export-fidelity assertions.
//   * lens_shift. The GUI exposes no control for it, so there is no user-visible value the export
//     could be dishonest about.
//   * The exposure anchor. See kScenes[] below: both scenes pin relative EV, and the reason is a
//     property of absolute mode, not an evasion.
//
// Platform reach — do not read a green CI as a green here. gui_test is COMPILED on macOS, Windows
// and Linux but RUN by exactly one CI leg (.github/workflows/ci.yml, Ubuntu x86_64 under xvfb-run
// with Mesa llvmpipe), and that leg passes a hand-picked positive filter that names only two
// reference groups. This category is not in it, in company with most of this binary's categories,
// so today NO CI job executes this fixture. The two pytest legs build with -DBUILD_GUI=OFF and do
// not have the binary at all. Where it does run is a developer machine with a working GL context:
// ./scripts/test.sh {quick,full,pr} runs the correctness pool, which includes this category.
//
// This is also the first place in the repo where a test binary starts the CLI binary as a child
// process. See RunCliRender below for the mechanics and for what that costs in portability.

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

#include "gui/gui_constants.hpp"
#include "include/lumice.h"
#include "test_gui_shared.hpp"

namespace {

struct ParityScene {
  const char* name;
  // Renderer fields, applied on top of the loaded document.
  int lens_type;
  float fov;
  float azimuth;
  float elevation;
  float roll;
  int visible;
  float background_srgb[3];
  // Display-group framing.
  gui::AspectPreset aspect_preset;
  bool aspect_portrait;
  // The one overlay core can also draw.
  bool show_horizon;
  // Ray budget, in millions. Must be a dyadic fraction so ExpectedSimRayNum's truncation and
  // rounding agree — see its note in test_gui_shared.hpp.
  float ray_num_millions;
  double psnr_threshold;
  // What the export arm must compute for the canvas, asserted before the images are compared so a
  // size disagreement is reported as itself rather than as a PSNR failure.
  int expect_w;
  int expect_h;
};

// Both scenes share one document (halo_22.json: prism crystals, sun at 20 degrees) and differ only
// in how it is framed, so a PSNR drop localizes to the framing rather than to the scene.
//
// EXPOSURE. Both scenes pin relative EV, overriding the absolute the document asks for, and that
// is a statement about what absolute mode promises rather than a convenience. Absolute mode anchors
// on emitted energy and normalizes by the frame's own pixel COUNT
// (src/server/render.cpp::ExposureScale, src/gui/mono_exposure_scale.hpp), so the brightness it
// produces is a function of the canvas and the lens. The GUI preview's pixels come from the
// full-sky simulation texture and are scaled by THAT texture's pixel count; the CLI renders the
// scene's own lens directly into the exported canvas and scales by its. The two therefore differ
// by a fixed factor whenever the exported canvas is not the simulation texture's own shape — which
// is exactly the "comparable only at equal lens / FOV / resolution" boundary doc/
// ev-pipeline-architecture.md states for absolute mode, not a defect this fixture should be
// reporting. Relative mode has no such term: both sides self-anchor on their own frame, so the
// residual is a difference of anchor POPULATION (percentile over the whole sky vs over the framed
// view), which is bounded and, being the same thing a user sees, part of what is under test.
//
// RAY BUDGET / SIM RESOLUTION. Both sides trace their own independent run: the noise is a real
// part of the comparison and is not to be removed by pinning a seed on either side (owner
// decision). What CAN be traded is how much of it there is, which is what the budget below buys;
// the threshold beside it is measured, not chosen. See the calibration note above each row.
constexpr int kSimResolutionIndex = 0;  // 512 -> a 1024x512 dual-equal-area simulation texture

// clang-format off
const ParityScene kScenes[] = {
  {"single_lens_angled",
   lumice::gui::kLensTypeFisheyeEqualArea, 96.0f, 25.0f, 30.0f, 15.0f, lumice::gui::kVisibleFull,
   /*background_srgb=*/{ 0.10f, 0.16f, 0.28f },
   gui::AspectPreset::k4x3, /*aspect_portrait=*/true, /*show_horizon=*/true,
   /*ray_num_millions=*/8.0f, /*psnr_threshold=*/10.0, /*expect_w=*/512, /*expect_h=*/683},
  {"full_sky_dual_fisheye",
   lumice::gui::kLensTypeDualFisheyeEqualArea, 180.0f, 25.0f, 30.0f, 15.0f, lumice::gui::kVisibleFull,
   /*background_srgb=*/{ 0.28f, 0.14f, 0.10f },
   gui::AspectPreset::kFree, /*aspect_portrait=*/false, /*show_horizon=*/false,
   /*ray_num_millions=*/8.0f, /*psnr_threshold=*/10.0, /*expect_w=*/1024, /*expect_h=*/512},
};
// clang-format on
constexpr int kSceneCount = sizeof(kScenes) / sizeof(kScenes[0]);

// Same shape and same reason as the guard in test/gui/visual/test_gui_lens_projection.cpp: every
// IM_CHECK* below can return early, and only a destructor tears down a running server and restores
// a widened watchdog on that path.
struct ScopedServerAndWatchdogGuard {
  ImGuiTestEngineIO* engine_io;
  float saved_watchdog_warn;
  float saved_watchdog_kill;
  bool server_owned = true;

  explicit ScopedServerAndWatchdogGuard(ImGuiTestEngineIO* io)
      : engine_io(io), saved_watchdog_warn(io->ConfigWatchdogWarning), saved_watchdog_kill(io->ConfigWatchdogKillTest) {
  }

  ~ScopedServerAndWatchdogGuard() {
    engine_io->ConfigWatchdogWarning = saved_watchdog_warn;
    engine_io->ConfigWatchdogKillTest = saved_watchdog_kill;
    if (server_owned && gui::g_server != nullptr) {
      gui::g_server_poller.Stop();
      LUMICE_StopServer(gui::g_server);
      LUMICE_DestroyServer(gui::g_server);
      gui::g_server = nullptr;
      gui::g_state.run_intent = gui::RunIntent::kNone;
    }
  }
};

// The canvas and the renderer id the exported config asks for. Parsed rather than recomputed: the
// canvas the GUI capture is taken at has to come from the export itself, or the comparison would
// be between two pictures that agreed only because the test computed the same number twice.
struct ExportedRenderInfo {
  int width = 0;
  int height = 0;
  int renderer_id = -1;
  bool ok = false;
};

ExportedRenderInfo ParseExportedRenderInfo(const std::string& json_str) {
  ExportedRenderInfo info;
  nlohmann::json root = nlohmann::json::parse(json_str, nullptr, /*allow_exceptions=*/false);
  if (root.is_discarded() || !root.contains("render") || !root["render"].is_array() || root["render"].empty()) {
    return info;
  }
  const auto& jr = root["render"][0];
  if (!jr.contains("resolution") || !jr["resolution"].is_array() || jr["resolution"].size() != 2) {
    return info;
  }
  info.width = jr["resolution"][0].get<int>();
  info.height = jr["resolution"][1].get<int>();
  info.renderer_id = jr.value("id", 0);
  info.ok = info.width > 0 && info.height > 0;
  return info;
}

// Run the CLI binary on `config_path`, writing into `out_dir`.
//
// std::system, not a spawn API: this is the only child process in the test tree, and the two
// platform families it has to work on both hand the string to a shell that treats a double-quoted
// argument the same way. Every path is quoted because this repository is routinely checked out
// under a directory with a space in it. The command line is echoed to stderr on failure, which is
// what makes a failure reproducible by hand; test/ is outside the scope of the no-bare-print gate
// for exactly this kind of harness diagnostic.
//
// LUMICE_CLI_BIN_PATH is a generator expression resolved at configure time
// (test/gui/CMakeLists.txt). A generator expression is only a string, so that file also declares a
// build dependency on the CLI target — without it, this would happily run whatever binary happened
// to be left over from a previous build, or none.
bool RunCliRender(const std::string& config_path, const std::string& out_dir) {
  const std::string cmd = "\"" LUMICE_CLI_BIN_PATH "\" -f \"" + config_path + "\" -o \"" + out_dir + "\" --format png";
  const int rc = std::system(cmd.c_str());
  if (rc != 0) {
    fprintf(stderr, "[export_parity] CLI render failed (rc=%d): %s\n", rc, cmd.c_str());
    return false;
  }
  return true;
}

}  // namespace

void RegisterExportParityTests(ImGuiTestEngine* engine) {
  for (int idx = 0; idx < kSceneCount; idx++) {
    ImGuiTest* t = IM_REGISTER_TEST(engine, "export_parity", kScenes[idx].name);
    t->ArgVariant = idx;
    t->TestFunc = [](ImGuiTestContext* ctx) {
      const auto& scene = kScenes[ctx->Test->ArgVariant];
      ResetTestState();

      gui::g_server = LUMICE_CreateServer();
      ScopedServerAndWatchdogGuard guard(ctx->EngineIO);
      LUMICE_SetLogLevel(gui::g_server, static_cast<LUMICE_LogLevel>(g_core_log_level));

      // 1. Load the document exactly as the product does when a .json is opened
      // (src/gui/app.cpp DoOpen -> DeserializeFromJson, which resets GuiState internally).
      {
        std::ifstream in(LUMICE_E2E_CONFIG_DIR "/halo_22.json");
        IM_CHECK(in.is_open());
        const std::string json_str((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
        IM_CHECK(gui::DeserializeFromJson(json_str, gui::g_state));
      }

      // 2. Apply the scene. These are writes to GuiState only — no PreviewParams is touched here,
      // because the whole point is to let the production per-frame assembly do that translation.
      {
        auto& rc = gui::g_state.renderer;
        rc.lens_type = scene.lens_type;
        rc.fov = scene.fov;
        rc.azimuth = scene.azimuth;
        rc.elevation = scene.elevation;
        rc.roll = scene.roll;
        rc.visible = scene.visible;
        rc.front = false;
        rc.ev_mode = 0;  // relative; see the exposure note above kScenes[]
        rc.exposure_offset = 0.0f;
        std::copy(std::begin(scene.background_srgb), std::end(scene.background_srgb), std::begin(rc.background));
        rc.sim_resolution_index = kSimResolutionIndex;
      }
      gui::g_state.aspect_preset = scene.aspect_preset;
      gui::g_state.aspect_portrait = scene.aspect_portrait;
      gui::g_state.show_horizon_line = scene.show_horizon;
      gui::g_state.sim.infinite = false;
      gui::g_state.sim.ray_num_millions = scene.ray_num_millions;

      // 3. Run to completion. kDone means the backend reported the committed epoch complete, so the
      // capture below is taken on a fixed amount of work rather than on whatever a poll happened to
      // pick up. The wall-clock deadline (and the watchdog raised out of its way) is the same
      // arrangement the lens-projection suite arrived at: under --fixed-dt the engine's watchdog
      // measures SIMULATED time and can fire while a real-time budget still has minutes left.
      gui::DoRun(/*user_initiated=*/true);
      IM_CHECK_EQ((int)gui::g_state.run_intent, (int)gui::RunIntent::kRunning);
      guard.engine_io->ConfigWatchdogWarning = 50000.0f;
      guard.engine_io->ConfigWatchdogKillTest = 100000.0f;
      const auto wait_deadline = std::chrono::steady_clock::now() + std::chrono::seconds(170);
      while (gui::g_state.sim_state != gui::GuiState::SimState::kDone &&
             std::chrono::steady_clock::now() < wait_deadline) {
        ctx->Yield(1);
      }
      IM_CHECK_EQ((int)gui::g_state.sim_state, (int)gui::GuiState::SimState::kDone);
      IM_CHECK_EQ((unsigned long long)gui::g_state.stats_sim_ray_num, ExpectedSimRayNum(scene.ray_num_millions));

      // 4. Let the product's own per-frame assembly fill g_preview_vp.params from GuiState. This is
      // the step that makes the GUI side of this comparison the real one: src/gui/app_panels.cpp
      // reads lens/fov/view/visible/background/horizon out of GuiState every frame, and it is that
      // translation — not a hand-written copy of it — that has to agree with the export.
      //
      // Asserted, not assumed: the assembly is gated on the preview owning a texture, so "the
      // frames went by" is not evidence it ran.
      ctx->Yield(3);
      IM_CHECK(gui::g_preview.HasTexture());
      IM_CHECK(gui::g_preview_vp.active);
      // The full-sky branch of that same assembly zeroes the three view angles. Reading it back
      // here states which side of the branch this scene is on before anything is rendered.
      if (gui::LensIsFullSky(scene.lens_type)) {
        IM_CHECK_EQ(gui::g_state.renderer.elevation, 0.0f);
        IM_CHECK_EQ(gui::g_state.renderer.azimuth, 0.0f);
        IM_CHECK_EQ(gui::g_state.renderer.roll, 0.0f);
      } else {
        IM_CHECK_EQ(gui::g_state.renderer.elevation, scene.elevation);
      }

      // 5. The export, through the production builder. A scene that reaches this point must not be
      // one the builder refuses (only the front-hemisphere clip is refused, and no scene sets it).
      std::string export_json;
      std::string warning;
      IM_CHECK(gui::BuildExportJsonOrWarn(gui::g_state, &export_json, &warning));
      const ExportedRenderInfo info = ParseExportedRenderInfo(export_json);
      IM_CHECK(info.ok);
      IM_CHECK_EQ(info.width, scene.expect_w);
      IM_CHECK_EQ(info.height, scene.expect_h);

      const std::filesystem::path scratch_dir =
          GuiTestTempPath(std::string("export_parity_") + scene.name).parent_path() /
          (std::string("export_parity_") + scene.name);
      std::error_code ec;
      std::filesystem::create_directories(scratch_dir, ec);
      IM_CHECK(!ec);
      const std::filesystem::path json_path = scratch_dir / "export.json";
      {
        std::ofstream out(json_path);
        IM_CHECK(out.is_open());
        out << export_json;
      }

      // 6. The GUI image, at the canvas the export just asked for. The params are the ones the
      // product assembled; only the output size is imposed, and it is imposed from the export so
      // both pictures land on the same pixel grid.
      gui::PreviewViewport vp = gui::g_preview_vp;
      vp.vp_w = info.width;
      vp.vp_h = info.height;
      const std::string gui_png = (scratch_dir / "gui.png").string();
      IM_CHECK(RequestAndWaitPreviewExport(ctx, vp, gui_png));

      // 7. Stop the server before handing the machine to the child process: the CLI is about to
      // want every core it can get, and nothing below needs the server.
      guard.server_owned = false;
      gui::g_server_poller.Stop();
      LUMICE_StopServer(gui::g_server);
      LUMICE_DestroyServer(gui::g_server);
      gui::g_server = nullptr;
      gui::g_state.run_intent = gui::RunIntent::kNone;

      // 8. The CLI image. The filename carries the renderer id the exported document states, not a
      // hardcoded 0 — src/main.cpp names its output after that id.
      IM_CHECK(RunCliRender(json_path.string(), scratch_dir.string()));
      char cli_name[32];
      snprintf(cli_name, sizeof(cli_name), "img_%02d.png", info.renderer_id);
      const std::string cli_png = (scratch_dir / cli_name).string();

      // 9. Compare. A size disagreement is a finding in its own right and is reported as one
      // rather than absorbed by a resize.
      std::vector<unsigned char> gui_data;
      std::vector<unsigned char> cli_data;
      int gw = 0;
      int gh = 0;
      int gc = 0;
      int cw = 0;
      int ch = 0;
      int cc = 0;
      IM_CHECK(lumice::test::LoadPng(gui_png.c_str(), gui_data, gw, gh, gc));
      IM_CHECK(lumice::test::LoadPng(cli_png.c_str(), cli_data, cw, ch, cc));
      IM_CHECK_EQ(gw, cw);
      IM_CHECK_EQ(gh, ch);
      IM_CHECK_EQ(cc, 3);
      std::vector<unsigned char> gui_rgb = gc == 4 ? lumice::test::StripAlpha(gui_data.data(), gw, gh) : gui_data;
      const double psnr = lumice::test::ComputePsnr(gui_rgb.data(), cli_data.data(), gw, gh, 3);
      // Same "[<group>] <tag>: PSNR=" spelling every other pixel comparison in this binary prints,
      // so one grep finds them all. Deliberately not routed through CheckAgainstReference: that
      // function's subject is a committed reference file, which this suite does not have.
      fprintf(stderr, "[export_parity] %s: PSNR=%.2f dB (threshold=%.1f dB) size=%dx%d\n", scene.name, psnr,
              scene.psnr_threshold, gw, gh);
      IM_CHECK_GE(psnr, scene.psnr_threshold);

      if (!g_keep_export_png) {
        std::filesystem::remove_all(scratch_dir, ec);
      }
    };
  }
}
