// Audit tests for Crystal::ReduceRaypath orbit invariant property.
//
// Background (scratchpad/scrum-filter-architecture-refactor/explore-reduce-raypath-audit/):
//   Task #209 fixed sigma_a≠0 + P+D canonicalization but covered only one case.
//   This audit systematically verifies orbit invariant across 5 dimensions:
//     H1: prism + kSymP + sigma_a≠0
//     H2: kSymB (basal 1↔2 + pyramid upper↔lower)
//     H3: pyramid crystal (双位编码 face_id 13..18/23..28)
//     H4: multi-segment (rp.size up to kMaxHits=8)
//     H5: mixed crystal type config
//
// Orbit invariant property:
//   For any raypath rp and any g in the symmetry group G generated by the active
//   symmetries, ReduceRaypath(rp) == ReduceRaypath(g·rp). The orbit {g·rp : g ∈ G}
//   is enumerated via Crystal::ExpandRaypath. Every orbit member must reduce to
//   the same canonical representative.
//
// On failure: this audit produces a minimal repro (failing orbit member + the two
// distinct canonicals) — the same pattern as #209's fix scope.

#include <gtest/gtest.h>

#include <string>
#include <vector>

#include "config/filter_config.hpp"
#include "core/crystal.hpp"
#include "core/def.hpp"

namespace lumice {
namespace {

// Format a raypath vector for diagnostic output.
std::string FormatRaypath(const std::vector<IdType>& rp) {
  std::string s = "{";
  for (size_t i = 0; i < rp.size(); i++) {
    if (i > 0) {
      s += ", ";
    }
    s += std::to_string(rp[i]);
  }
  s += "}";
  return s;
}

// Verify the orbit invariant for one (crystal, symmetry, sigma_a, d_applicable, rp_seed) tuple.
// Returns ::testing::AssertionResult so EXPECT_TRUE prints the failing detail.
::testing::AssertionResult VerifyOrbitInvariant(const Crystal& crystal, uint8_t symmetry, int sigma_a,
                                                bool d_applicable, const std::vector<IdType>& rp_seed) {
  auto canonical_seed = crystal.ReduceRaypath(rp_seed, symmetry, sigma_a, d_applicable);
  auto orbit = crystal.ExpandRaypath(rp_seed, symmetry, sigma_a, d_applicable);
  if (orbit.empty()) {
    return ::testing::AssertionFailure() << "ExpandRaypath returned empty orbit for seed " << FormatRaypath(rp_seed);
  }
  for (const auto& member : orbit) {
    auto canonical_member = crystal.ReduceRaypath(member, symmetry, sigma_a, d_applicable);
    if (canonical_member != canonical_seed) {
      return ::testing::AssertionFailure()
             << "Orbit invariant broken:" << "\n  seed:               " << FormatRaypath(rp_seed)
             << "\n  seed canonical:     " << FormatRaypath(canonical_seed)
             << "\n  orbit member:       " << FormatRaypath(member)
             << "\n  member canonical:   " << FormatRaypath(canonical_member)
             << "\n  symmetry=" << static_cast<int>(symmetry) << " sigma_a=" << sigma_a
             << " d_applicable=" << d_applicable;
    }
  }
  return ::testing::AssertionSuccess();
}

}  // namespace

// ============================================================================
// H2: kSymB orbit invariant
// ============================================================================
// kSymB encodes basal 1↔2 + pyramid upper [13..18]↔lower [23..28]; prism faces unchanged.
// Coverage: B-only / P+B / D+B / P+D+B across prism and pyramid crystals.

TEST(H2_KSymB_Audit, BasalReflect_Prism) {
  // Prism with basal+prism raypath: B flips basal 1↔2, prism face unchanged.
  Crystal prism = Crystal::CreatePrism(1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymB, 0, false, { 1, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymB, 0, false, { 2, 7 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymB, 0, false, { 1, 3, 2 }));
}

TEST(H2_KSymB_Audit, BasalAndPyramidReflect_Pyramid) {
  // Pyramid with basal+upper raypath: B flips basal 1↔2 AND pyramid 13↔23.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymB, 0, false, { 1, 13 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymB, 0, false, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymB, 0, false, { 23, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymB, 0, false, { 1, 13, 5, 23 }));
}

TEST(H2_KSymPB_Audit, PrismRaypath_Prism) {
  // P+B on prism: P rotates prism pri, B flips basal — independent symmetries.
  Crystal prism = Crystal::CreatePrism(1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, false, { 3, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, false, { 1, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, false, { 1, 3, 5 }));
}

TEST(H2_KSymPB_Audit, MixedRaypath_Pyramid) {
  // P+B on pyramid with basal+upper+prism: full interaction.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, false, { 1, 13 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, false, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, false, { 1, 13, 5 }));
}

TEST(H2_KSymDB_Audit, PrismRaypath_Prism) {
  // D+B on prism (sigma_a=0): D rotates prism pri via reflection, B flips basal.
  Crystal prism = Crystal::CreatePrism(1.0f);
  uint8_t sym = FilterConfig::kSymD | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 3, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 1, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 1, 3, 7 }));
}

TEST(H2_KSymDB_Audit, MixedRaypath_Pyramid) {
  // D+B on pyramid: D reflects pri on prism + pyramid (same pri arithmetic),
  // B flips basal + upper↔lower pyramid. Most complex single-pair interaction.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymD | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13, 5, 23 }));
}

TEST(H2_KSymPDB_Audit, FullSymmetry_Prism) {
  // P+D+B on prism: full hexagonal symmetry group.
  Crystal prism = Crystal::CreatePrism(1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymD | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 3, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 1, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 5, true, { 3, 5 }));  // non-zero sigma_a
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 1, 3, 5, 7 }));
}

TEST(H2_KSymPDB_Audit, FullSymmetry_Pyramid) {
  // P+D+B on pyramid: full symmetry group including upper↔lower pyramid swap.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymD | FilterConfig::kSymB;
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13, 5, 23 }));
}

// ============================================================================
// H1: prism + kSymP + sigma_a ≠ 0 orbit invariant
// ============================================================================
// sigma_a only enters the D block; with kSymP alone, sigma_a should be ignored.
// Test guards against accidental sigma_a leakage from external callers.

TEST(H1_KSymP_SigmaA_Audit, SigmaA_Ignored_Prism) {
  Crystal prism = Crystal::CreatePrism(1.0f);
  // Same orbit invariant should hold across sigma_a ∈ {0, 1, 3, 5} and d_applicable both flags.
  for (int sigma_a : { 0, 1, 3, 5 }) {
    for (bool d_applicable : { false, true }) {
      EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymP, sigma_a, d_applicable, { 3, 5 }))
          << "sigma_a=" << sigma_a << " d_applicable=" << d_applicable;
      EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymP, sigma_a, d_applicable, { 1, 5, 7 }))
          << "sigma_a=" << sigma_a << " d_applicable=" << d_applicable;
    }
  }
}

TEST(H1_KSymP_SigmaA_Audit, SigmaA_Ignored_Pyramid) {
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  for (int sigma_a : { 0, 1, 3, 5 }) {
    for (bool d_applicable : { false, true }) {
      EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, sigma_a, d_applicable, { 13, 5 }))
          << "sigma_a=" << sigma_a << " d_applicable=" << d_applicable;
      EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, sigma_a, d_applicable, { 1, 13, 5 }))
          << "sigma_a=" << sigma_a << " d_applicable=" << d_applicable;
    }
  }
}

// Cross-check: sigma_a affects only D block, so canonical for kSymP must be sigma_a-independent.
TEST(H1_KSymP_SigmaA_Audit, Canonical_Independent_of_SigmaA) {
  Crystal prism = Crystal::CreatePrism(1.0f);
  std::vector<IdType> rp = { 3, 5 };
  auto baseline = prism.ReduceRaypath(rp, FilterConfig::kSymP, 0, false);
  for (int sigma_a : { 0, 1, 3, 5 }) {
    for (bool d_applicable : { false, true }) {
      auto canonical = prism.ReduceRaypath(rp, FilterConfig::kSymP, sigma_a, d_applicable);
      EXPECT_EQ(canonical, baseline) << "sigma_a=" << sigma_a << " d_applicable=" << d_applicable;
    }
  }
}

// ============================================================================
// H3: pyramid crystal (双位编码 face_id 13..18 / 23..28) orbit invariant
// ============================================================================
// Pyramid encoding: pyr * 10 + pri where pyr ∈ {0=prism, 1=upper, 2=lower}.
// Key audit dimensions:
//   - pyr part preservation through P shift (only pri rotated)
//   - pyr part preservation through D reflect (only pri reflected)
//   - first_pri detection on multi-pyramid raypath (which segment sets first_pri?)
//   - pyramid-only raypath orbit (no prism faces, no basal)

TEST(H3_PyramidEncoding_Audit, UpperPyramidOnly_P) {
  // raypath of pure upper pyramid faces; verifies P shift preserves pyr=1.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 13, 15 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 14, 16, 18 }));
}

TEST(H3_PyramidEncoding_Audit, LowerPyramidOnly_P) {
  // raypath of pure lower pyramid faces; verifies P shift preserves pyr=2.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 23, 25 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 24, 26, 28 }));
}

TEST(H3_PyramidEncoding_Audit, MixedUpperLowerPyramid_P) {
  // upper + lower pyramid mixed; first_pri is from first non-basal segment.
  // For {13, 23}: first_pri = 3 (from 13). Then face 23: pri = 23 % 10 = 3,
  // shift by 6-3=3 → (3+3)%6+3 = 0+3 = 3. Wait, let me recompute.
  // first_pri logic: first non-basal segment's pri = x % 10. For face 13: pri = 13 % 10 = 3.
  // For face 23: pri = 23 % 10 = 3. shift: (3 + 6 - 3) % 6 + 3 = 6 % 6 + 3 = 3. So 23 → 2*10+3 = 23 ✓
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 13, 23 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 18, 28, 14 }));
}

TEST(H3_PyramidEncoding_Audit, PyramidWithPrism_P) {
  // Mixed pyramid + prism; first_pri determined by leftmost prism-or-pyramid face.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 13, 5 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 5, 13 }));  // order matters for first_pri
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, { 1, 13, 5, 23 }));
}

TEST(H3_PyramidEncoding_Audit, PyramidOnly_D) {
  // Pyramid-only raypath under D; pyr part should pass through D reflection unchanged.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymD, 0, true, { 13, 15 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymD, 0, true, { 23, 25 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymD, 0, true, { 13, 23 }));
  // sigma_a ≠ 0 with D
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymD, 3, true, { 13, 15 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymD, 5, true, { 18, 28 }));
}

TEST(H3_PyramidEncoding_Audit, PyramidOnly_PD) {
  // P+D on pure pyramid raypath; verifies combined pyr-preservation + pri-correctness.
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymD;
  for (int sigma_a : { 0, 1, 3, 5 }) {
    EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, sigma_a, true, { 13, 15 })) << "sigma_a=" << sigma_a;
    EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, sigma_a, true, { 23, 25 })) << "sigma_a=" << sigma_a;
    EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, sigma_a, true, { 13, 23 })) << "sigma_a=" << sigma_a;
    EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, sigma_a, true, { 18, 5, 28 })) << "sigma_a=" << sigma_a;
  }
}

// ============================================================================
// H4: multi-segment (rp.size ∈ [3, kMaxHits=8]) orbit invariant
// ============================================================================
// Key risk: PCanonicalShift's `first_pri` is determined by the first non-basal
// segment and applied uniformly to all remaining segments. If implementation
// accidentally reset first_pri per-segment or mixed coordinate, multi-segment
// raypaths would break orbit invariant.

TEST(H4_MultiSegment_Audit, LongPrismOnly_PD) {
  Crystal prism = Crystal::CreatePrism(1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymD;
  // 5-segment all prism, mixed pri values
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 3, 5, 7, 4, 8 }));
  // 6-segment with repeats (raypath that loops through prism faces)
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 3, 5, 3, 5, 3, 5 }));
  // 8-segment (kMaxHits) all prism
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 0, true, { 3, 4, 5, 6, 7, 8, 3, 4 }));
  // 7-segment with sigma_a ≠ 0
  EXPECT_TRUE(VerifyOrbitInvariant(prism, sym, 5, true, { 3, 4, 5, 6, 7, 8, 3 }));
}

TEST(H4_MultiSegment_Audit, LongMixed_FullSymmetry_Pyramid) {
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  uint8_t sym = FilterConfig::kSymP | FilterConfig::kSymD | FilterConfig::kSymB;
  // 5-segment mixing basal + prism + pyramid (upper + lower)
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13, 5, 23, 7 }));
  // 6-segment heavy pyramid
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 13, 14, 15, 23, 24, 25 }));
  // 8-segment (kMaxHits) max stress
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 0, true, { 1, 13, 5, 23, 7, 14, 2, 24 }));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, sym, 5, true, { 1, 13, 5, 23, 7, 14, 2, 24 }));
}

// ============================================================================
// H5: mixed crystal type config — per-crystal canonical isolation
// ============================================================================
// FilterSpec in C2 holds per-crystal canonical. Crystal is a value type with
// per-instance fn_map_/fn_period_/poly_face_data, so isolation is by design.
// This sanity test verifies no sneaky shared state exists.

TEST(H5_MixedCrystal_Audit, PrismPyramidIsolation) {
  Crystal prism = Crystal::CreatePrism(1.0f);
  Crystal pyramid = Crystal::CreatePyramid(1.0f, 1.0f, 1.0f);
  std::vector<IdType> rp = { 3, 5 };

  // Same raypath, same symmetry, different crystals — both should be valid canonical
  // representatives of their respective orbits. They may equal each other (because
  // {3,5} prism orbit overlaps the pyramid {3,5} prism-only orbit), but the audit
  // verifies neither crystal pollutes the other.
  auto canonical_prism_alone = prism.ReduceRaypath(rp, FilterConfig::kSymP, 0, false);
  auto canonical_pyramid_alone = pyramid.ReduceRaypath(rp, FilterConfig::kSymP, 0, false);

  // Compute interleaved to detect any shared state.
  auto canonical_prism_2 = prism.ReduceRaypath(rp, FilterConfig::kSymP, 0, false);
  auto canonical_pyramid_2 = pyramid.ReduceRaypath(rp, FilterConfig::kSymP, 0, false);
  auto canonical_prism_3 = prism.ReduceRaypath(rp, FilterConfig::kSymP, 0, false);

  // Same crystal must give identical canonical.
  EXPECT_EQ(canonical_prism_alone, canonical_prism_2);
  EXPECT_EQ(canonical_prism_alone, canonical_prism_3);
  EXPECT_EQ(canonical_pyramid_alone, canonical_pyramid_2);

  // Each crystal's orbit invariant still holds.
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymP, 0, false, rp));
  EXPECT_TRUE(VerifyOrbitInvariant(pyramid, FilterConfig::kSymP, 0, false, rp));
}

TEST(H5_MixedCrystal_Audit, PyramidFacesRejectedByPrism) {
  // pyramid face (e.g., 13) on a prism crystal is technically not a valid face,
  // but ReduceRaypath should still produce some deterministic result without crash.
  Crystal prism = Crystal::CreatePrism(1.0f);
  std::vector<IdType> rp_pyramid_face = { 13, 5 };
  auto canonical = prism.ReduceRaypath(rp_pyramid_face, FilterConfig::kSymP, 0, false);
  // The result is implementation-defined; we just check the call doesn't crash and
  // is deterministic across calls.
  auto canonical_again = prism.ReduceRaypath(rp_pyramid_face, FilterConfig::kSymP, 0, false);
  EXPECT_EQ(canonical, canonical_again);
}

TEST(H4_MultiSegment_Audit, FirstPriProvenance_PD) {
  // Test that first_pri is correctly determined and applied uniformly.
  // raypath {3, 5, 7}: first_pri = 3 (from face 3). All shifts: face 5 → (5+6-3)%6+3 = 5,
  // face 7 → (7+6-3)%6+3 = 7. Canonical: {3, 5, 7} (already canonical, first_pri=3).
  // raypath {5, 7, 3}: first_pri = 5 (from face 5). face 5 → 3, face 7 → 5, face 3 → 7.
  // So {5,7,3} should reduce to same orbit canonical as {3,5,7}? Only if under P symmetry
  // they are in the same orbit (yes, they are P-rotations of each other when seed is rotated).
  // Wait, {5,7,3} P-shift by -2 gives {3,5,1}? Let me verify with orbit invariant test.
  Crystal prism = Crystal::CreatePrism(1.0f);
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymP, 0, false, { 3, 5, 7 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymP, 0, false, { 5, 7, 3 }));
  EXPECT_TRUE(VerifyOrbitInvariant(prism, FilterConfig::kSymP, 0, false, { 7, 3, 5 }));
  // These three should reduce to the SAME canonical (they're in the same P-orbit).
  auto c1 = prism.ReduceRaypath({ 3, 5, 7 }, FilterConfig::kSymP, 0, false);
  auto c2 = prism.ReduceRaypath({ 5, 7, 3 }, FilterConfig::kSymP, 0, false);
  auto c3 = prism.ReduceRaypath({ 7, 3, 5 }, FilterConfig::kSymP, 0, false);
  // Wait — {3,5,7}, {5,7,3}, {7,3,5} are different sequences (segment ORDER matters).
  // P-shift on {3,5,7} by k gives {3+k, 5+k, 7+k} mod 6 (with +3 offset). So {3,5,7} and
  // {5,7,3} are P-related: shift by 2 gives {5,7,9 mod 6 + 3} = {5,7,3}. Yes!
  EXPECT_EQ(c1, c2);
  EXPECT_EQ(c1, c3);
}

}  // namespace lumice
