#!/usr/bin/env python3
"""Embed a binary file as a C++ byte array.

Usage: embed_binary.py <input> <output.cpp> <symbol_prefix>

Emits a .cpp that defines:
  namespace lumice::gui {
  const unsigned char <prefix>Data[N] = { ... };
  const std::size_t  <prefix>Size = N;
  }

The corresponding header is hand-written (see fa_solid_900_embed.h).
"""

from __future__ import annotations

import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <input> <output.cpp> <symbol_name>", file=sys.stderr)
        return 1

    in_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    symbol = sys.argv[3]

    data = in_path.read_bytes()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("// Auto-generated by scripts/embed_binary.py — do not edit.")
    lines.append("// Source: " + in_path.name)
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("namespace lumice::gui {")
    lines.append("")
    lines.append(f"extern const unsigned char {symbol}Data[];")
    lines.append(f"extern const std::size_t {symbol}Size;")
    lines.append("")
    lines.append(f"const unsigned char {symbol}Data[] = {{")

    chunk = 16
    for i in range(0, len(data), chunk):
        row = ", ".join(f"0x{b:02x}" for b in data[i : i + chunk])
        lines.append(f"    {row},")
    lines.append("};")
    lines.append("")
    lines.append(f"const std::size_t {symbol}Size = {len(data)};")
    lines.append("")
    lines.append("}  // namespace lumice::gui")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
