#!/usr/bin/env python3
"""Embed Metal artifacts (pre-compiled .metallib + .metal source) as C headers.

Usage:
  embed_metal_artifacts.py \\
      --metallib <input.metallib> \\
      --metal-src <input.metal> \\
      --out-dir <output_directory>

Produces two header files in the output directory:

  lumice_trace_metallib_embed.h
    namespace lumice {
    inline constexpr unsigned char kLumiceMetallibBytes[] = { 0x.., ... };
    inline constexpr std::size_t   kLumiceMetallibSize = N;
    }

  lumice_trace_src_embed.h
    namespace lumice {
    inline constexpr char kLumiceCombinedKernelSrc[] = "...";
    }

The source string is the verbatim contents of the .metal file (which is the
single source of truth, byte-equivalent to the legacy `%s\\n%s` concatenation
of kFilterMatchHelperSrc + kKernelSrc). The string is emitted as a single
escaped C string literal so `newLibraryWithSource(@(kLumiceCombinedKernelSrc))`
works as a fallback in pre-26.5 environments.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def emit_bytes_header(metallib_path: Path, out_path: Path) -> None:
    data = metallib_path.read_bytes()
    lines: list[str] = []
    lines.append("// Auto-generated by scripts/embed_metal_artifacts.py — do not edit.")
    lines.append(f"// Source: {metallib_path.name} ({len(data)} bytes)")
    lines.append("#pragma once")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("namespace lumice {")
    lines.append("")
    lines.append("inline constexpr unsigned char kLumiceMetallibBytes[] = {")
    chunk = 16
    for i in range(0, len(data), chunk):
        row = ", ".join(f"0x{b:02x}" for b in data[i : i + chunk])
        lines.append(f"    {row},")
    lines.append("};")
    lines.append("")
    lines.append(f"inline constexpr std::size_t kLumiceMetallibSize = {len(data)};")
    lines.append("")
    lines.append("}  // namespace lumice")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def c_escape(src_bytes: bytes) -> str:
    """Escape a UTF-8 byte sequence as a C/C++ "..." string literal.

    Byte-level (NOT code-point-level) escape: non-ASCII bytes (e.g. multi-byte
    UTF-8 for Chinese comments) are emitted as 3-digit octal escapes so each
    byte maps to a single C-string byte. Octal escapes are always 3 digits to
    prevent greedy consumption of following digit characters. Newlines split
    the literal into per-line chunks for readability.
    """
    out: list[str] = []
    out.append('"')
    for b in src_bytes:
        if b == 0x5C:  # backslash
            out.append("\\\\")
        elif b == 0x22:  # double quote
            out.append('\\"')
        elif b == 0x0A:  # newline
            out.append('\\n"\n"')
        elif b == 0x09:  # tab
            out.append("\\t")
        elif b == 0x0D:  # carriage return
            out.append("\\r")
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            # Non-ASCII / control byte: 3-digit octal (always exactly 3 digits
            # so adjacent ASCII digits cannot extend the escape).
            out.append(f"\\{b:03o}")
    out.append('"')
    return "".join(out)


def emit_source_header(metal_src_path: Path, out_path: Path) -> None:
    src_bytes = metal_src_path.read_bytes()
    escaped = c_escape(src_bytes)
    lines: list[str] = []
    lines.append("// Auto-generated by scripts/embed_metal_artifacts.py — do not edit.")
    lines.append(f"// Source: {metal_src_path.name} ({len(src_bytes)} bytes UTF-8)")
    lines.append("#pragma once")
    lines.append("")
    lines.append("namespace lumice {")
    lines.append("")
    lines.append("inline constexpr char kLumiceCombinedKernelSrc[] =")
    lines.append(escaped + ";")
    lines.append("")
    lines.append("}  // namespace lumice")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--metallib", required=True, type=Path)
    parser.add_argument("--metal-src", required=True, type=Path)
    parser.add_argument("--out-dir", required=True, type=Path)
    args = parser.parse_args()

    if not args.metallib.is_file():
        print(f"error: --metallib not found: {args.metallib}", file=sys.stderr)
        return 1
    if not args.metal_src.is_file():
        print(f"error: --metal-src not found: {args.metal_src}", file=sys.stderr)
        return 1

    args.out_dir.mkdir(parents=True, exist_ok=True)
    emit_bytes_header(args.metallib, args.out_dir / "lumice_trace_metallib_embed.h")
    emit_source_header(args.metal_src, args.out_dir / "lumice_trace_src_embed.h")
    return 0


if __name__ == "__main__":
    sys.exit(main())
